### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by Zyles** [rtheunissen/guzzle-cache-handler#1]
Some more docs would be nice. Example on how to specify cacheprovider and handler for example with a simple filecache or something.

Never used Doctrine before.

Thanks.

**Comment by rtheunissen** [comment]
I'm updating the cache interface anyway so I'll add some more detailed docs when I do. I'll let you know when it's done (no later than tomorrow).

**Comment by rtheunissen** [comment]
I've added a basic example in 9d914439799dc56454f0acec505c8e8a4b0580fe, which is now reflected in v0.5.0. Let me know if you're having trouble.

:+1:

**Comment by Zyles** [comment]
Yes sadly I am still facing issues.

The cache is saved on file system but I get this error that Guzzle can not read the contents now:

```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getBody() on a non-object in /home/httpd/website/index.php on line 81" while reading response header from upstream
```

Code is pretty simple:

```
try {
    $response = $client->get('get?' . http_build_query($args));
    $json = $response->getBody()->getContents();
...
```

Thanks.
