### ISSUE TITLE
Can you please tag a new version?

### ISSUE THREAD

**Issue by antoniopaisfernandes** [rtheunissen/guzzle-cache-handler#13]
Having support for Guzzle 7, a new tag would help upgrade other packages that depend on `guzzle-cache-handler`.

Thank you 😄

**Comment by antoniopaisfernandes** [comment]
@rtheunissen Sorry for bothering you. 😢 

Is it possible to tag a new version?

**Comment by rtheunissen** [comment]
Tagged v2.0.0 -- apologies that this project was neglected during a busy time in my life.

**Comment by antoniopaisfernandes** [comment]
🙏
