### ISSUE TITLE
Only cache responses with valid status code

### ISSUE THREAD

**Issue by Zyles** [rtheunissen/guzzle-cache-handler#5]
Just creating a new issue here for reference.

I did some research and i think it would be good to only cache responses with a status code of 200.

Imagine this scenario:

You make a request that returns an invalid status like 500, 404 or any other error type. This will be cached. And lets say your cache is set to 1 day. This would render the Guzzle proxy unusable for an entire day always returning an invalid response even if the endpoint gets running again. 

But if you did not cache an error response, the next time the request is made and the endpoint is hopefully working the valid cache will be saved and it will work despite the cache duration.

What do you think?

**Comment by rtheunissen** [comment]
If you look at `shouldCacheResponse`, you will see `$response->getStatusCode() < 400`. By default, any response with a status code at 400 and above will not be cached. 

There is also `shouldCacheRequest` which does something similar. By default, POST should not be cached anyway. POST request are not idempotent. However it does make sense to cache GET, OPTIONS and HEAD requests. There is a constructor option for which methods to cache.

You're welcome to override any of this behaviour though. :)
