### ISSUE TITLE
Should the key be a hash?

### ISSUE THREAD

**Issue by tplaner** [rtheunissen/guzzle-cache-handler#7]
Some keys can be extremely long which can cause problems with different cache stores.

Should the handler create keys which are hashes? Or is that not the responsibility of this library?

**Comment by rtheunissen** [comment]
Do you have an example of a cache store which has trouble with long keys? I woudn't be opposed to making the key a hash if there's a good reason for it.

**Comment by tplaner** [comment]
Using the Illuminate adaptor with a database cache store, the default cache table migration uses a `key` that is a unique string with a length of 255 characters.

I've thought about this a little bit more and I do think that Laravel should be hashing all keys anyway both for a performance boost and to avoid issues like this. I'm probably going to work on a pull request to implement hashing of cache keys on their end.

However, I have already made modification to a custom `IlluminateAdapter` which makes this change. I would be happy to submit it as a pull request. Alternatively I could implement the change within the `CacheHandler`. Let me know.

I think a `sha1` hash of the key should be sufficient though it could be easily configurable. Collisions with hashes are possible though I believe they are more of a concern for binary data.

**Comment by rtheunissen** [comment]
I think that this is up to the cache store, though I think a hash on the handler side isn't a bad idea either. Right now it's not possible for there to be a collision because the URI, method, and request options literally make up the key.
