### ISSUE TITLE
Add filter to shouldCacheResponse

### ISSUE THREAD

**Issue by rafis** [rtheunissen/guzzle-cache-handler#8]
There is filter to make decision `shouldCacheRequest` and this filter for making decision by Request. Can you please add similar filter for Response. For example, Google detects bots and shows captcha and I don't want such responses to be cached. Currenlty I have to extend `CacheHandler` class to do that.

If you will implement this also consider changing declaration to include request `protected function shouldCacheResponse(Request $request, Response $response)`.

**Comment by rtheunissen** [comment]
Added and tagged as v2.0.0 alongside some other fixes. Only about 7 years too late. ><
