### ISSUE TITLE
Beware: not ETag support

### ISSUE THREAD

**Issue by andig** [rtheunissen/guzzle-cache-handler#9]
Just a heads up as I got stuck at this point working with the Spotify API: this library does not honor etags. Would be good to clearly mention this on the front page.

**Comment by rtheunissen** [comment]
Doesn't this fall on Guzzle instead?

**Comment by andig** [comment]
Don't think so as Guzzle doesn't implement caching itself. I've switched the cache solution now, see here for a sample setup including a library with etag support: https://github.com/andig/spotify-web-api-extensions
